### ISSUE TITLE
2.0.0 Version

### ISSUE THREAD

**Issue by juergen-albert** [eclipse-emfcloud/emfjson-jackson#16]
With the recent changes, it would be nice if you race the Version to 2.0.0 as, the rename of the packages marks a major change to the API.

**Comment by planger** [comment]
Agreed, we'll trigger the release review with the Eclipse foundation team soon. This new release should then be a 2.0.
The current changes are only available via the nightly builds yet, so it isn't really a release yet.

**Comment by martin-fleck-at** [comment]
Hello, we recently received the official go ahead from the Eclipse PMC so we can now continue our work on the release. If there are no unexpected problems the release should go live in December.

**Comment by martin-fleck-at** [comment]
Release available here: https://github.com/eclipse-emfcloud/emfjson-jackson/releases/tag/v2.0.0
