### ISSUE TITLE
Saving JSON to memory

### ISSUE THREAD

**Issue by ftomassetti** [eclipse-emfcloud/emfjson-jackson#3]
Hi, do you know how could I save a model as a JSON string? I mean, a string that I have in memory, not on file?

**Comment by castortech** [comment]
This will serialize an EObject to string:
```
ObjectMapper mapper = new ObjectMapper();
EMFModule module = new EMFModule();
mapper.registerModule(module);
String jsonString = mapper.writeValueAsString(myEObject);

```

**Comment by eneufeld** [comment]
Thanks @castortech and @hallvard for your answers. @ftomassetti I hope this solved your issue. Please reopen if questions remain.

**Comment by ftomassetti** [comment]
Thank you!
