### ISSUE TITLE
Why my json has incomplete URIs for Eclasses?

### ISSUE THREAD

**Issue by ftomassetti** [eclipse-emfcloud/emfjson-jackson#4]
I am getting this JSON:
```
{
  "eClass" : "#//Result",
  "root" : {
    "eClass" : "#//CompilationUnit",
    "statements" : [ {
      "eClass" : "#//VarDeclaration",
      "initialValue" : {
        "eClass" : "#//StringLiteral",
        "value" : "foo"
      },
      "name" : "a"
    }, {
      "eClass" : "#//VarDeclaration",
      "initialValue" : {
        "eClass" : "#//StringLiteral",
        "value" : "bar"
      },
      "name" : "b",
      "visibility" : "PRIVATE"
    } ]
  },
  "issues" : [ {
    "message" : "lex",
    "position" : {
      "start" : {
        "line" : 1,
        "column" : 1
      },
      "end" : {
        "line" : 2,
        "column" : 10
      }
    }
  }, {
    "message" : "foo"
  } ]
}
```

I would expect the EClasses to have complete URIs, based on the URI of the containing packages instead of having the form `#//Result"`. Is there something I should do to get that result?

**Comment by martin-fleck-at** [comment]
@ftomassetti How are you getting this JSON? From what I can see we use the full eClass-URI (`EcoreUtil.getURI`) by default, as specified in the `EcoreTypeInfo` of the EMFModule. If no URI has been specified anywhere elseYou can adapt the serialization of the type by specifying a different type info, see [CustomSerializersTest](https://github.com/eclipse-emfcloud/emfjson-jackson/blob/fd4d1f7ab21ba9775a5f20b7708fad7ae189c3ab/src/test/java/org/eclipse/emfcloud/jackson/tests/custom/CustomSerializersTest.java#L79).

**Comment by martin-fleck-at** [comment]
@ftomassetti Absolutely understandable and thank you for your fast response!

**Comment by eneufeld** [comment]
Please feel free to reopen if issue persists.
