### ISSUE TITLE
EMFModule.Feature.OPTION_SERIALIZE_CONTAINMENT_AS_HREF does not have any effect

### ISSUE THREAD

**Issue by juergen-albert** [eclipse-emfcloud/emfjson-jackson#48]
The EMFModule can be configured with different Features and one of them is
https://github.com/eclipse-emfcloud/emfjson-jackson/blob/e6bf66250b1a93045722864497d0233ffc521439/src/main/java/org/eclipse/emfcloud/jackson/module/EMFModule.java#L98

I've looked for the usage of the Feature and found none. Thus I assume it is not implemented for whatever reason.
As far as I understand it, containment objects would be serialized as proxies. I'm not sure how this might produce a meaningful URI accept maybe for cross-document containments but this is besides the point.  Does somebody know the intention behind this Feature and the question would be if it can be removed or if it would be forth it to implement it.

**Comment by martin-fleck-at** [comment]
That is a very good question! It seems that this option was originally introduced with [5 other options in the previous repository](https://github.com/emfjson/emfjson-jackson/commit/d5cc0dad40cc4e60b250b9a99c483546b40732df) but only four of those options actually made it [into the 1.0 release back then](https://github.com/emfjson/emfjson-jackson/commit/f556077ce014251a6a2a8812b16f028a009730ab#diff-58d2ef8f83447753457d575e060cf917d879538765ea36fde54e063f64e69344). Still, it seems to me that this option was never implemented and so far nobody has had any use for it. If you need it, we are happy to accept contributions but if you do not need it I would almost opt to remove that feature.

**Comment by martin-fleck-at** [comment]
@juergen-albert I'll remove the option for now. If you think it is valuable, please feel free to open a PR for it.

**Comment by juergen-albert** [comment]
Sorry for my late reply and thanks for your quick reaction. Removing it would have been my choice as well.
