### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by gg-dim** [eclipse-emfcloud/emfjson-jackson#60]
Hello,
Can we please get a new release with the fixes of the last months?

thx and best regards
Guido

**Comment by martin-fleck-at** [comment]
Hi @gg-dim, do you need a new release or would it be possible for you to use the current snapshot versions as well? Snapshot versions are built on every merge to master so they should always be up to date and you should also be able to specify a specific version if need be.

- P2 Nightly Snapshot: https://download.eclipse.org/emfcloud/emfjson-jackson/p2/nightly/2.2/
- Maven Snapshot: https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/emfcloud/emfjson-jackson/2.2.0-SNAPSHOT/

**Comment by gg-dim** [comment]
Hi @martin-fleck-at 
It's fine for development. But as a dependency in production or in releases of other projects, a released version would be desirable.

**Comment by martin-fleck-at** [comment]
@gg-dim I understand. I believe I should be able to create a new release this week or early next week.

**Comment by martin-fleck-at** [comment]
@gg-dim I new release is available: https://github.com/eclipse-emfcloud/emfjson-jackson/releases/tag/v2.2.0

**Comment by gg-dim** [comment]
thx
